# Digit Recognizer

#### Load Dependencies

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import keras
from keras.layers import Dense, Dropout, Flatten, MaxPooling2D,Conv2D
from keras.models import Sequential
from keras.optimizers import adam

Using TensorFlow backend.


In [2]:
data = pd.read_csv('train.csv')

In [3]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [4]:
labels = data['label'].values

In [5]:
data.describe()

label   pixel0   pixel1   pixel2   pixel3   pixel4   pixel5  \
count  42000.000000  42000.0  42000.0  42000.0  42000.0  42000.0  42000.0   
mean       4.456643      0.0      0.0      0.0      0.0      0.0      0.0   
std        2.887730      0.0      0.0      0.0      0.0      0.0      0.0   
min        0.000000      0.0      0.0      0.0      0.0      0.0      0.0   
25%        2.000000      0.0      0.0      0.0      0.0      0.0      0.0   
50%        4.000000      0.0      0.0      0.0      0.0      0.0      0.0   
75%        7.000000      0.0      0.0      0.0      0.0      0.0      0.0   
max        9.000000      0.0      0.0      0.0      0.0      0.0      0.0   

        pixel6   pixel7   pixel8    ...         pixel774      pixel775  \
count  42000.0  42000.0  42000.0    ...     42000.000000  42000.000000   
mean       0.0      0.0      0.0    ...         0.219286      0.117095   
std        0.0      0.0      0.0    ...         6.312890      4.633819   
min        0.0      0.0      0.0    ...         0.000000      0.000000   
25%        0.0      0.0      0.0    ...         0.000000      0.000000   
50%        0.0      0.0      0.0    ...         0.000000      0.000000   
75%        0.0      0.0      0.0    ...         0.000000      0.000000   
max        0.0      0.0      0.0    ...       254.000000    254.000000   

           pixel776     pixel777      pixel778      pixel779  pixel780  \
count  42000.000000  42000.00000  42000.000000  42000.000000   42000.0   
mean       0.059024      0.02019      0.017238      0.002857       0.0   
std        3.274488      1.75987      1.894498      0.414264       0.0   
min        0.000000      0.00000      0.000000      0.000000       0.0   
25%        0.000000      0.00000      0.000000      0.000000       0.0   
50%        0.000000      0.00000      0.000000      0.000000       0.0   
75%        0.000000      0.00000      0.000000      0.000000       0.0   
max      253.000000    253.00000    254.000000     62.000000       0.0   

       pixel781  pixel782  pixel783  
count   42000.0   42000.0   42000.0  
mean        0.0       0.0       0.0  
std         0.0       0.0       0.0  
min         0.0       0.0       0.0  
25%         0.0       0.0       0.0  
50%         0.0       0.0       0.0  
75%         0.0       0.0       0.0  
max         0.0       0.0       0.0  

[8 rows x 785 columns]

In [6]:
pixels = data.iloc[:,data.columns != 'label'].values

In [7]:
pixels

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [8]:
pixels = pixels.reshape(42000,28,28,1).astype('float32')
pixels /= 255


In [9]:
label_classes = keras.utils.to_categorical(labels,10)

In [10]:
label_classes

array([[ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [11]:
model = Sequential()
model.add(Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=(28,28,1)))
model.add(Conv2D(64,kernel_size=(3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10,activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])



In [12]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 12, 12, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 9216)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               1179776   
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
__________

In [3]:
bool(0)

False

In [13]:
model.fit(pixels,label_classes,epochs=20,verbose=2,batch_size=50)

Epoch 1/20
 - 181s - loss: 0.4553 - acc: 0.8563
Epoch 2/20
 - 188s - loss: 0.1645 - acc: 0.9557
Epoch 3/20
 - 179s - loss: 0.1179 - acc: 0.9687
Epoch 4/20
 - 182s - loss: 0.0982 - acc: 0.9730
Epoch 5/20
 - 195s - loss: 0.0836 - acc: 0.9769
Epoch 6/20
 - 196s - loss: 0.0748 - acc: 0.9793
Epoch 7/20
 - 195s - loss: 0.0664 - acc: 0.9825
Epoch 8/20
 - 196s - loss: 0.0571 - acc: 0.9845
Epoch 9/20
 - 194s - loss: 0.0503 - acc: 0.9856
Epoch 10/20
 - 186s - loss: 0.0462 - acc: 0.9865
Epoch 11/20
 - 202s - loss: 0.0474 - acc: 0.9869
Epoch 12/20
 - 200s - loss: 0.0446 - acc: 0.9877
Epoch 13/20
 - 192s - loss: 0.0405 - acc: 0.9886
Epoch 14/20
 - 184s - loss: 0.0359 - acc: 0.9896
Epoch 15/20
 - 178s - loss: 0.0343 - acc: 0.9898
Epoch 16/20
 - 186s - loss: 0.0323 - acc: 0.9905
Epoch 17/20
 - 181s - loss: 0.0318 - acc: 0.9907
Epoch 18/20
 - 202s - loss: 0.0277 - acc: 0.9919
Epoch 19/20
 - 177s - loss: 0.0273 - acc: 0.9920
Epoch 20/20
 - 173s - loss: 0.0287 - acc: 0.9912


In [14]:
test_data= pd.read_csv('test.csv')

In [15]:
test_data.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [16]:
test_pixels= test_data.values
test_pixels.shape

(28000, 784)

In [17]:
test_pixels = test_pixels.reshape(28000,28,28,1).astype('float32')

In [18]:
test_pixels.shape

(28000, 28, 28, 1)

In [19]:
output = model.predict(test_pixels)

In [20]:
output.shape

(28000, 10)

In [21]:
from sklearn.preprocessing import LabelEncoder
from numpy import argmax
label_encoder= LabelEncoder()
inverse = output.argmax(1)

In [22]:
inverse

array([2, 0, 9, ..., 3, 9, 2], dtype=int64)

In [23]:
predictions=inverse

In [24]:
submissions=pd.DataFrame({"ImageId": list(range(1,len(predictions)+1)),
                         "Label": predictions})
submissions.to_csv("submission.csv", index=False, header=True)